# Mob Spawn Controls Settings
#
# This file is used to keep track of various MSC settings
#
# readOnly=(true/false)
#
readOnly=false
#
# canEditInGame=(true/false)
#
canEditInGame=false
#
# masterEnabled=(true/false)
#
masterEnabled=true
#
# creatureSpawnFrequency=(int)
#
creatureSpawnFrequency=400
#
# Cap.(monster/creature/waterCreature/ambient)=(int)
#
Cap.monster=50
Cap.creature=20
Cap.ambient=15
Cap.waterCreature=15
#
